### ISSUE TITLE
[iOS Crash] Exception has occurred: CLR/System.InvalidOperationException

### ISSUE THREAD

**Issue by omrkcmn** [AdamEssenmacher/MemoryToolkit.Maui#24]
it works fine on android but when you switch to IOS debug or release mode the app crashes with the following error.

```
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.iOS.dll: 'Unable to convert Microsoft.Maui.Controls.StackLayout to UIKit.UIView'
   at UIKit.UIApplication.xamarin_UIApplicationMain(Int32 argc, IntPtr argv, IntPtr principalClassName, IntPtr delegateClassName, IntPtr& gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at XXX.Program.Main(String[] args) in /XXX/Documents/Github/XXX/XXX/Platforms/iOS/Program.cs:line 14
```

MyPage.xaml

`xmlns:mtk="clr-namespace:MemoryToolkit.Maui;assembly=MemoryToolkit.Maui"
mtk:LeakMonitorBehavior.Cascade="True"
mtk:TearDownBehavior.Cascade="True" `

MauiProgram.cs

`#if DEBUG
            // Configure logging
            builder.Logging.AddDebug();

            // Ensure UseLeakDetection is called after logging has been configured!
            builder.UseLeakDetection(collectionTarget =>
            {
                // This callback will run any time a leak is detected.
                // Application.Current?.MainPage?.DisplayAlert("⚠️ eyvah eyvah ⚠️",
                //     $"❗🧟❗{collectionTarget.Name} kalmış!", "OK");
            });

            builder.Logging.AddDebug();
            builder.EnableHotReload();
#endif`

**Comment by pmahend1** [comment]
Same here. Did you find a work-around?

**Comment by omrkcmn** [comment]
> Same here. Did you find a work-around?

No, I updated the package and it fixed itself

**Comment by pmahend1** [comment]
@omrkcmn Oh. Great! What version did you update it to? I am on the latest stable nuget and it is .NET MAUI

**Comment by omrkcmn** [comment]
> [@omrkcmn](https://github.com/omrkcmn) Oh. Great! What version did you update it to? I am on the latest stable nuget and it is .NET MAUI

1.0
